steps:
  # Build & push auth
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/levomart/levomart/auth:latest",
        "./auth",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-south1-docker.pkg.dev/levomart/levomart/auth:latest"]

images:
  - "asia-south1-docker.pkg.dev/levomart/levomart/auth:latest"
