spring.application.name=payment
server.port=5000
logging.level.org.springframework.security=DEBUG
spring.docker.compose.enabled=false

# PostgreSQL  Database Configuration
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/mydb

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.session.cookie.same-site=strict
spring.security.user.name=
spring.security.user.password=


# Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${WEBHOOK_SECRET_KEY}
CHECKOUT_SUCCESS_URL=${CHECKOUT_SUCCESS_URL}
CHECKOUT_CANCEL_URL=${CHECKOUT_CANCEL_URL}
jwt.secret=${JWT_KEY}

# Kafka
kafka.address=${KAFKA_BROKERS}
kafka.topic.paymentSucceeded=payment-succeeded
kafka.paymentSucceeded.schema=../shared-schemas/payment/payment-succeeded.schema.json
kafka.topic.paymentFailed=payment-failed










