steps:
  # Build & push product
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/levomart/levomart/product:latest",
        "./product",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "asia-south1-docker.pkg.dev/levomart/levomart/product:latest"]

  - "asia-south1-docker.pkg.dev/levomart/levomart/product:latest"
