apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  MONGO_URI: mongodb://product-mongo-service:27017/productdb
  PORT: "4000"
  KAFKA_CLIENT_ID: product-service
  KAFKA_BROKERS_ADDRESS: kafka:9092
