spring.application.name=cart
server.port=8081
logging.level.org.springframework.security=DEBUG
# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

jwt.secret=${JWT_KEY}
server.servlet.session.cookie.same-site=strict
spring.docker.compose.enabled=false
spring.security.user.name=
spring.security.user.password=
logging.aop.verbose:false
